# Generated by Django 5.2.15 on 2026-06-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_kart', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
