# Generated by Django 5.2.15 on 2026-06-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_kart', '0008_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_code',
            field=models.CharField(default='#000000', help_text='Hex color code, e.g. #1db947', max_length=7),
        ),
    ]
