# Generated by Django 5.2.15 on 2026-06-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_kart', '0015_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_buy_now_available',
            field=models.BooleanField(default=True, help_text='If enabled, shows Buy Now button to purchase immediately'),
        ),
    ]
