# Generated by Django 5.2.14 on 2026-06-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_kart', '0016_product_is_buy_now_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
