# Generated by Django 5.2.15 on 2026-07-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_kart', '0021_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Unique stock keeping unit', max_length=50, null=True, unique=True),
        ),
    ]
