# Generated by Django 5.2.15 on 2026-07-04 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy_kart', '0022_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_code',
        ),
    ]
