# Generated by Django 5.2.15 on 2026-07-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_kart', '0023_remove_product_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Available stock quantity'),
        ),
    ]
