# Generated by Django 5.2.15 on 2026-07-04 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_kart', '0024_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default='Guest', max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=5)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='easy_kart.product')),
            ],
            options={
                'verbose_name': 'Product Feedback',
                'verbose_name_plural': 'Product Feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
