# Generated by Django 5.2.15 on 2026-07-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy_kart', '0025_productfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('easy_kart.product',),
        ),
    ]
