# Generated by Django 5.2.14 on 2026-07-08 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_kart', '0026_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order for related products')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products_from', to='easy_kart.product')),
                ('related_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products_to', to='easy_kart.product')),
            ],
            options={
                'verbose_name': 'Related Product',
                'verbose_name_plural': 'Related Products',
                'ordering': ['order', '-created_at'],
                'unique_together': {('product', 'related_to')},
            },
        ),
    ]
