# Generated by Django 5.2.15 on 2026-07-14 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_kart', '0028_cart_session_key_alter_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to='easy_kart.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Help Request',
                'verbose_name_plural': 'Product Help Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
