# Generated by Django 5.2.15 on 2026-07-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_kart', '0029_producthelprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeedback',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
