# Generated by Django 5.2.15 on 2026-08-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_kart', '0032_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
    ]
