# Generated by Django 5.2.12 on 2026-08-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_kart', '0033_customuser_username_delete_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shape',
            field=models.CharField(blank=True, help_text='Product shape (e.g., Square, Round, Rectangular)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='Product size (e.g., S, M, L, XL or 10cm x 10cm)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, help_text='Product weight (e.g., 500g, 1kg, 2lbs)', max_length=100, null=True),
        ),
    ]
