# Generated by Django 5.2.14 on 2026-10-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_kart', '0034_product_shape_product_size_product_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('password_hash', models.CharField(max_length=128)),
                ('otp_hash', models.CharField(max_length=128)),
                ('otp_expires_at', models.DateTimeField()),
                ('last_sent_at', models.DateTimeField()),
                ('resend_window_started_at', models.DateTimeField()),
                ('resend_count', models.PositiveSmallIntegerField(default=0)),
                ('verification_attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email_otp_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
